name: Build and Deploy

on:
  push:
    branches:
      - main   # jalankan otomatis kalau ada push ke branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy to deploy branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan deploy
          git --work-tree build add --all
          git --work-tree build commit -m "Deploy from GitHub Actions"
          git push origin HEAD:deploy --force
